apiVersion: apps/v1
kind: Deployment
metadata:
  name: vikunja
  namespace: vikunja
  labels:
    app: vikunja
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: vikunja
  template:
    metadata:
      labels:
        app: vikunja
    spec:
      containers:
      - name: vikunja
        image: vikunja/vikunja:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3456
        env:
        - name: VIKUNJA_DATABASE_HOST
          value: postgres.vikunja.svc.cluster.local
        - name: VIKUNJA_DATABASE_PORT
          value: "5432"
        - name: VIKUNJA_DATABASE_USER
          value: vikunja
        - name: VIKUNJA_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: VIKUNJA_DATABASE_TYPE
          value: postgres
        - name: VIKUNJA_DATABASE_DATABASE
          value: vikunjadb
        livenessProbe:
          httpGet:
            path: /health
            port: 3456
          initialDelaySeconds: 3
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3456
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3