apiVersion: v1
kind: Service
metadata:
  name: vikunja
  labels:
    app: vikunja
spec:
  type: ClusterIP
  selector:
    app: vikunja
  ports:
    - port: 80           # Port exposed by the service
      targetPort: 3456   # Port exposed by the Vikunja container
